language: node_js
node_js:
  - 14 # uses version 14
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "deployment-exercise-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: foxydingo
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: C30P+BPgqizbTKjbKEat9G1T/fNXOLIHmtBMrrspQV25kum6aLszrPtaAxHOapEWYQo2nFSq/3+fSH40LWdoXH79ZuSaEVMdJ8j7sHj5w68092chEIHzLE+en5SKZoIxqfn2GZftPjPhnFYiNNm3mAxHf2OCpOnQI4+ySmecTC02s1IsBBc2Iq0oUjWfgtb/dSkJLrn7pLGRz+mmfoywpolxYqYcCPFBA1JtstDvvOuK7lHiJAJ2pvF/5eIA/lOHNgj1lDO8QBrZBmfiw/GO3dcIqqwO1RSf1XBy9N3HLI5afMFYCBGD8/R7mpTaCTlB9USem3LzHJOCUefSr6YpXwhi4QcGAOpq02dIahS8UbqVMPtYvhS4/xRtrF5ziiUpOT7quUwjyGkz5nkfK9EeYZZccnGl8sFfZxzV5SUdNIU/Xci7+2eO2Kied+IBKBfvZhD66h06tGV/4qzqo+vtUpCv9K1b1IHOdJhVRkqWbZXTzuE98USOLS/EPg11C0gKd8sf0KZrqn+DD1HLY7J0D44iDuZi9qQVv2k8vvKcz55DimYKzkcsn3qCkQ0NPyjG5jeOa+EpecRWB9AlcgR0Jd1PnacnjJ61wRZxTros3jg9zz6gi7BAk/ikC3dEiBAEUyNW7KqFgNirdLv1tjB53bNCzPr/E+mXrEf4hUFayWc=
